# Uber Customer Segmentation CI/CD Pipeline

name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run unit tests
        run: |
          pip install pytest
          pytest tests/

      - name: Run training script
        run: |
          PYTHONPATH=. python src/models/train_minibatch_kmeans.py

      - name: Upload clustering results
        uses: actions/upload-artifact@v4
        with:
          name: clustering-results
          path: data/minibatch_kmeans_clusters.csv
